# Configuration settings for the Entangler gateware.
# Allows configuring the number of inputs & outputs, counter widths, etc.

# I believe these can be overwritten by setting the same-named environment variable,
# if you cannot modify this file for some reason.

[development]
# NOTE: if you would like an "entangler_is_running" output, decrease NUM_OUTPUT_CHANNELS by 1
NUM_OUTPUT_CHANNELS = 12
NUM_ENTANGLER_INPUT_SIGNALS = 4
NUM_PATTERNS_ALLOWED = 4

# These ones probably shouldn't need changed, but leaving it here just in case
# Width of sequence duration counters and the coarse part of input timestamps
# (units of clock cycles).
COARSE_COUNTER_WIDTH = 11
# COUNTER_WIDTH + fine_timestamp_width = 11 + 3 = 14
# Limited in various places to be <= 16 bits, probably don't do more than that.
FULL_COUNTER_WIDTH = 14
MAX_CYCLES_PER_RUN = 16383  # 14 bits
MAX_TRIGGER_COUNTS = 16383  # 14 bits
